export const CARD_TYPES = {
     VIEW_INFO_CARD : 'VIEW_INFO_CARD',
     CHANGES_TASKS: 'CHANGES_TASKS',
     CLEAR_INFO_CARD: 'CLEAR_INFO_CARD',
     CHANGE_DESCRIPTION :'CHANGE_DESCRIPTION',
     CHANGE_DECISION_DATE: 'CHANGE_DECISION_DATE'
}
