export const COLUMNS_TYPES = {
  VIEW_ALL_COLUMNS: "VIEW_ALL_COLUMNS",
  VIEW_ALL_COLUMNS2: "VIEW_ALL_COLUMNS2",
  ADD_NEW_COLUMN: "ADD_NEW_COLUMN",
  UPDATE_COLUMN: "UPDATE_COLUMN",
  VIEW_ADD_CARDS: "VIEW_ADD_CARDS",
  GET_TASK_INFO: "GET_TASK_INFO"
};
