export const BOARD_TYPES = {
  VIEW_BOARD: "VIEW_BOARD",
  VIEW_ALL_BOARD: "VIEW_ALL_BOARD",
  ADD_NEW_BOARD: "ADD_NEW_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  UPDATE_ALL_BOARD: "UPDATE_ALL_BOARD",
  CHANGE_IS_ERROR: "CHANGE_IS_ERROR",
  IS_LOADING_CHANGE: "IS_LOADING_CHANGE"
};
