export const BOARD_TYPES = {
  VIEW_BOARD: "VIEW_BOARD",
  VIEW_ALL_BOARD: "VIEW_ALL_BOARD",
  ADD_NEW_BOARD: "ADD_NEW_BOARD",
  UPDATE_BOARD: "UPDATE_BOARD",
  UPDATE_ALL_BOARD: "UPDATE_ALL_BOARD"
};
